stages:
  - kaniko
  - deploy

variables:
  APPNAME: "tosync"
  DOMAIN: "avapps.fr"
  ROOT_URL: "https://${APPNAME}.${DOMAIN}"
  IMAGE_TAG: "${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
  INFO: "[meteor-docker]"

before_script:
  - if [[ ${CI_COMMIT_REF_NAME} = "master" && $CI_COMMIT_TAG ]]; then IMAGE_TAG="stable-${CI_COMMIT_TAG}"; fi

kaniko-build:
  stage: kaniko
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo ${INFO} Starting docker image build with Kaniko for ${CI_COMMIT_REF_NAME} and pushing to ${IMAGE_TAG}
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${IMAGE_TAG}"
  only:
    - master
    - dev
    - dev-end
  tags:
    - docker

deploy-prod:
  stage: deploy
  trigger:
    project: kubernetes/avapps/tosync-meteor-chart
    strategy: depend
  variables:
    CHART_IMAGE_REGISTRY: "${CI_REGISTRY_IMAGE}"
    CHART_IMAGE_TAG: "${IMAGE_TAG}"
  environment:
    name: production
    url: https://tosync.avapps.fr
  when: manual
  only:
    - master

deploy-dev:
  stage: deploy
  trigger:
    project: kubernetes/avapps/tosync-meteor-chart
    strategy: depend
  variables:
    CHART_IMAGE_REGISTRY: "${CI_REGISTRY_IMAGE}"
    CHART_IMAGE_TAG: "${IMAGE_TAG}"
  environment:
    name: staging
    url: https://tosync.dev.avapps.fr
  only:
    - dev
    - dev-end
